/// <reference types="vite/client" />

/**
 * Type declarations for vite-plugin-pwa virtual modules
 * 
 * These modules are generated by vite-plugin-pwa at build time
 * and provide service worker registration functionality.
 */

declare module 'virtual:pwa-register' {
  export interface RegisterSWOptions {
    /**
     * Called when the registered service worker has installed but is waiting to activate.
     * @param reloadPage - Function to reload the page and activate the new SW
     */
    onNeedRefresh?: () => void;
    
    /**
     * Called when the app is ready to work offline
     */
    onOfflineReady?: () => void;
    
    /**
     * Called when there's an error during SW registration
     */
    onRegisterError?: (error: Error) => void;
    
    /**
     * Called when the SW is registered
     */
    onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
    
    /**
     * Whether to register SW immediately or wait for window load event
     */
    immediate?: boolean;
  }
  
  /**
   * Register the service worker
   * @returns Function to manually trigger update check
   */
  export function registerSW(options?: RegisterSWOptions): (reloadPage?: boolean) => Promise<void>;
}

declare module 'virtual:pwa-register/react' {
  import type { Dispatch, SetStateAction } from 'react';
  
  export interface RegisterSWOptions {
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
    onRegisterError?: (error: Error) => void;
    onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
    immediate?: boolean;
  }
  
  export function useRegisterSW(options?: RegisterSWOptions): {
    offlineReady: [boolean, Dispatch<SetStateAction<boolean>>];
    needRefresh: [boolean, Dispatch<SetStateAction<boolean>>];
    updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
  };
}
